# Numpy Fundamentals

Numpy (short for Numerical Python) is an open source python library for scientific computing.
The library contains a long list of useful mathematical functions
 - Linear algebra
 - Fourier transformation
 - Random Number generation, etc

Numpy's arrays are stored more efficiently than an equivalent data structure in base Python, the improvement in performance scales with the number of elements in the array.
The drawback of NumPy arrays is that they are more specialized than plain lists, hence outside of numerical computing, they are less useful.

In [7]:
import numpy as np
print("The numpy version is :: {}".format(np.__version__))

The numpy version is :: 1.19.4


In [11]:
# A Vector in the mathematical sense, a one dimensional array
# squares = [] that contains the squares of numbers 1 to n, including n
# pyhtonic
n = 10
squares = [i*i for i in range(1, n+1)]
print(squares)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [13]:
# numpy way
nsquares = np.arange(1, n+1) ** 2
print(nsquares)

[  1   4   9  16  25  36  49  64  81 100]


Numpy code requires less explicit loops than the equivalent Python Code

In [25]:
# Numpy arrays can be added directly without a for loop
odds = np.arange(1, n+1, 2)
print(odds)
evens = np.arange(2, n+1, 2)
print(evens)

elem_sum = odds + evens
print(elem_sum)
# Notice that numpy arrays are not comma seperated like list elements while printing them.

[1 3 5 7 9]
[ 2  4  6  8 10]
[ 3  7 11 15 19]


Concepts to get started with numpy
 - Data Types
 - Array Types
 - Type Conversions
 - Array Creation
 - Indexing
 - Slicing
 - Shape Manipulation