# Numpy Fundamentals

Numpy (short for Numerical Python) is an open source python library for scientific computing.
The library contains a long list of useful mathematical functions
 - Linear algebra
 - Fourier transformation
 - Random Number generation, etc

Numpy's arrays are stored more efficiently than an equivalent data structure in base Python, the improvement in performance scales with the number of elements in the array.
The drawback of NumPy arrays is that they are more specialized than plain lists, hence outside of numerical computing, they are less useful.

In [2]:
import numpy as np
print("The numpy version is :: {}".format(np.__version__))

The numpy version is :: 1.19.4


In [3]:
# A Vector in the mathematical sense, a one dimensional array
# squares = [] that contains the squares of numbers 1 to n, including n
# pyhtonic
n = 10
squares = [i*i for i in range(1, n+1)]
print(squares)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [4]:
# numpy way
nsquares = np.arange(1, n+1) ** 2
print(nsquares)

[  1   4   9  16  25  36  49  64  81 100]


Numpy code requires less explicit loops than the equivalent Python Code

In [5]:
# Numpy arrays can be added directly without a for loop
odds = np.arange(1, n+1, 2)
print(odds)
evens = np.arange(2, n+1, 2)
print(evens)

elem_sum = odds + evens
print(elem_sum)
# Notice that numpy arrays are not comma seperated like list elements while printing them.

[1 3 5 7 9]
[ 2  4  6  8 10]
[ 3  7 11 15 19]


Concepts to get started with numpy
 - Data Types
 - Array Types
 - Type Conversions
 - Array Creation
 - Indexing
 - Slicing
 - Shape Manipulation

In [6]:
# DATA TYPES
n = 10
ex = np.arange(1, n+1)
print("Array : ", ex)
print("Type is : " , type(ex))
# Numpy has a multidimensional array object called the ndarray. It consists of two parts
# 1. The actual data.
# 2. Metadata regarding the data.
# The numpy array is homogeneous in general i.e. all the items in the array are of the same type.
# The advantage of this property is that its easy to determine the size required of the array.
print("Data Type is :: ", ex.dtype)
# We have created a vector, a single dimension array consisting of int64 items.
# To know the dimensions/shape of a numpy array we can call the shape attribute
print("The shape of the array is : ", ex.shape)
# this returns us an tuple, which indicates the number of items or length in each dimension of the array.!!
multi_ex = np.array([np.arange(1, n+1, 2), np.arange(2, n+1, 2)])
print("A MultiDimensional Array ::: \n", multi_ex)
print("The data type of the multi dimensional array is :: ", multi_ex.dtype)
print("The shape of the mullti dimensional array is :: ", multi_ex.shape)

Array :  [ 1  2  3  4  5  6  7  8  9 10]
Type is :  <class 'numpy.ndarray'>
Data Type is ::  int64
The shape of the array is :  (10,)
A MultiDimensional Array ::: 
 [[ 1  3  5  7  9]
 [ 2  4  6  8 10]]
The data type of the multi dimensional array is ::  int64
The shape of the mullti dimensional array is ::  (2, 5)


### Some Common numpy datatypes with varying precision
| DataType      | Description |
| :---------- | ----------- |
| bool      | True/False stored as a bit       |
| int   | int32 or int64        |
| int8   | integer ( -2 ** 8 to 2 ** 8 -1)     |
| int16   | integer ( -2 ** 15 to 2 ** 15 -1)  |
| int32   | integer ( -2 ** 31 to 2 ** 31 -1)  |
| int64   | integer ( -2 ** 63 to 2 ** 63 -1)  |
| uint8   | unsigned integer 0-2**(8) -1       |
| uint16   | unsigned integer 0-2**(16)-1      |
| uint32   | unsigned integer 0-2**(32)-1      |
| uint64   | unsigned integer 0-2**(64)-1      |
| float16   | half precision float             |
| float32   | single precision float           |
| float64   | double precision float           |
| complex64   | complex number represented by two 32 bit floats        |
|----------- | ----------- |

The data type objects are instances of the numpy.dtype class. Arrays have a data type, the data type can tell the size of the data in bytesm using the itemsize attribute

In [7]:
print(multi_ex.dtype)
print("Size of item in bytes", multi_ex.dtype.itemsize)

int64
Size of item in bytes 8


In [8]:
# Creating the heterogeneous datatype
item_datatype = np.dtype([('name', str, 30), ("quantity", "int32"), ("cost", "float32")])
print("Custom Item DataType::: ", item_datatype)
items = np.array([("Pen", 20, 12.33), ("Blank Book", 100, 4.5), ("Pencil", 200, 1.56334)], dtype=item_datatype)
print(items)
print(items.shape)
print(items[0])

Custom Item DataType:::  [('name', '<U30'), ('quantity', '<i4'), ('cost', '<f4')]
[('Pen',  20, 12.33   ) ('Blank Book', 100,  4.5    )
 ('Pencil', 200,  1.56334)]
(3,)
('Pen', 20, 12.33)


In [9]:
# Accessing the elements of the array
n = 20
ex = np.array([np.arange(1, n+1, 2), np.arange(2, n+1, 2)])
print(ex)
print(ex.shape)

[[ 1  3  5  7  9 11 13 15 17 19]
 [ 2  4  6  8 10 12 14 16 18 20]]
(2, 10)


In [10]:
ex[0, 9] # ex[0, -1]

19

In [15]:
ex[0,2]

5

In [22]:
ex[:, 2:4]

array([[5, 7],
       [6, 8]])

In [25]:
ex[0:,]

array([[ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19],
       [ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20]])

In [26]:
ex[0:,...]

array([[ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19],
       [ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20]])

In [35]:
ex[:,1:6]

array([[ 3,  5,  7,  9, 11],
       [ 4,  6,  8, 10, 12]])

In [34]:
ex[:,1:6:2]

array([[ 3,  7, 11],
       [ 4,  8, 12]])

### Numpy array methods :
a - is the array
shape is the tuple representing the new shape of the array

 - np.arange(start, stop, step)
 - a.reshape((size))
 - np.resize(a, (shape)) -> returns the new array with the desired shape, adds the input elements again if required
 - a.flatten() -> returns a new array
 - a.ravel() -> returns the flat view of the array
 - a.transpose() -> returns a transpose of the array
 - np.hstack() -> function stacks arrays horizontally(axis=1)
 - np.vstack() -> Function stacks arrays vertically (axis=0)
 - np.concatenate() -> Function to stack the arrays based on the given axis
 - np.dstack() -> function stacks arrays depth wise along the third axis
 - np.row_stack() -> same as vstack()
 - np.column_stack() -> in 2d arrays same as hstack()

In [120]:
threeD = np.array([3, 6, 9, 2, 4, 6, 5, 10, 15, 7, 14, 21]).reshape(3,2,2)
threeD

array([[[ 3,  6],
        [ 9,  2]],

       [[ 4,  6],
        [ 5, 10]],

       [[15,  7],
        [14, 21]]])

In [121]:
# Note that ravel is just an view of the array in the flat structure, modifying this will affect the original array
threeD.ravel()

array([ 3,  6,  9,  2,  4,  6,  5, 10, 15,  7, 14, 21])

In [122]:
# Flatten will create a  new copy of the array and allocates new memory for it.
threeD.flatten()

array([ 3,  6,  9,  2,  4,  6,  5, 10, 15,  7, 14, 21])

In [123]:
threeD.transpose()
# Transposing a matrix entails flipping the matrix in such a manner, that the matrix rows become the matrix columns and vice versa

array([[[ 3,  4, 15],
        [ 9,  5, 14]],

       [[ 6,  6,  7],
        [ 2, 10, 21]]])

In [124]:
threeD

array([[[ 3,  6],
        [ 9,  2]],

       [[ 4,  6],
        [ 5, 10]],

       [[15,  7],
        [14, 21]]])

In [125]:
np.resize(threeD, (3,5))
# Reshape: Changes the shape of the array and adds copies of the input array if necessary

array([[ 3,  6,  9,  2,  4],
       [ 6,  5, 10, 15,  7],
       [14, 21,  3,  6,  9]])

In [126]:
a = np.arange(1, 200, 8).reshape(5,5)
a

array([[  1,   9,  17,  25,  33],
       [ 41,  49,  57,  65,  73],
       [ 81,  89,  97, 105, 113],
       [121, 129, 137, 145, 153],
       [161, 169, 177, 185, 193]])

In [127]:
a+a

array([[  2,  18,  34,  50,  66],
       [ 82,  98, 114, 130, 146],
       [162, 178, 194, 210, 226],
       [242, 258, 274, 290, 306],
       [322, 338, 354, 370, 386]])

In [128]:
3*a

array([[  3,  27,  51,  75,  99],
       [123, 147, 171, 195, 219],
       [243, 267, 291, 315, 339],
       [363, 387, 411, 435, 459],
       [483, 507, 531, 555, 579]])

In [129]:
b = a/2
b

array([[ 0.5,  4.5,  8.5, 12.5, 16.5],
       [20.5, 24.5, 28.5, 32.5, 36.5],
       [40.5, 44.5, 48.5, 52.5, 56.5],
       [60.5, 64.5, 68.5, 72.5, 76.5],
       [80.5, 84.5, 88.5, 92.5, 96.5]])

In [130]:
b.dtype, a.dtype

(dtype('float64'), dtype('int64'))

In [131]:
c = np.hstack((a,b))
c, c.shape
# same as the column_stack method for the 2d arrays

(array([[  1. ,   9. ,  17. ,  25. ,  33. ,   0.5,   4.5,   8.5,  12.5,
          16.5],
        [ 41. ,  49. ,  57. ,  65. ,  73. ,  20.5,  24.5,  28.5,  32.5,
          36.5],
        [ 81. ,  89. ,  97. , 105. , 113. ,  40.5,  44.5,  48.5,  52.5,
          56.5],
        [121. , 129. , 137. , 145. , 153. ,  60.5,  64.5,  68.5,  72.5,
          76.5],
        [161. , 169. , 177. , 185. , 193. ,  80.5,  84.5,  88.5,  92.5,
          96.5]]),
 (5, 10))

In [132]:
c.dtype

dtype('float64')

In [133]:
d = np.concatenate((a,b), axis=1)
d, d.shape

(array([[  1. ,   9. ,  17. ,  25. ,  33. ,   0.5,   4.5,   8.5,  12.5,
          16.5],
        [ 41. ,  49. ,  57. ,  65. ,  73. ,  20.5,  24.5,  28.5,  32.5,
          36.5],
        [ 81. ,  89. ,  97. , 105. , 113. ,  40.5,  44.5,  48.5,  52.5,
          56.5],
        [121. , 129. , 137. , 145. , 153. ,  60.5,  64.5,  68.5,  72.5,
          76.5],
        [161. , 169. , 177. , 185. , 193. ,  80.5,  84.5,  88.5,  92.5,
          96.5]]),
 (5, 10))

In [134]:
e = np.vstack((a,b))
e, e.shape
# same as the row_stack method for the 2d arrays

(array([[  1. ,   9. ,  17. ,  25. ,  33. ],
        [ 41. ,  49. ,  57. ,  65. ,  73. ],
        [ 81. ,  89. ,  97. , 105. , 113. ],
        [121. , 129. , 137. , 145. , 153. ],
        [161. , 169. , 177. , 185. , 193. ],
        [  0.5,   4.5,   8.5,  12.5,  16.5],
        [ 20.5,  24.5,  28.5,  32.5,  36.5],
        [ 40.5,  44.5,  48.5,  52.5,  56.5],
        [ 60.5,  64.5,  68.5,  72.5,  76.5],
        [ 80.5,  84.5,  88.5,  92.5,  96.5]]),
 (10, 5))

In [135]:
f = np.concatenate((a,b), axis=0)
f, f.shape

(array([[  1. ,   9. ,  17. ,  25. ,  33. ],
        [ 41. ,  49. ,  57. ,  65. ,  73. ],
        [ 81. ,  89. ,  97. , 105. , 113. ],
        [121. , 129. , 137. , 145. , 153. ],
        [161. , 169. , 177. , 185. , 193. ],
        [  0.5,   4.5,   8.5,  12.5,  16.5],
        [ 20.5,  24.5,  28.5,  32.5,  36.5],
        [ 40.5,  44.5,  48.5,  52.5,  56.5],
        [ 60.5,  64.5,  68.5,  72.5,  76.5],
        [ 80.5,  84.5,  88.5,  92.5,  96.5]]),
 (10, 5))

In [136]:
a = np.arange(0, 30).reshape(3,10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [137]:
a.shape # Shape of the array

(3, 10)

In [138]:
a.dtype.itemsize # size of each item in the array

8

In [139]:
a.ndim # Total number of dimensions in the array

2

In [140]:
a.size # The total numner of items in the array

30

In [141]:
a.nbytes # The total number of bytes the array requires, same as itemsize * size

240

In [142]:
a.T # same as a.transpose()

array([[ 0, 10, 20],
       [ 1, 11, 21],
       [ 2, 12, 22],
       [ 3, 13, 23],
       [ 4, 14, 24],
       [ 5, 15, 25],
       [ 6, 16, 26],
       [ 7, 17, 27],
       [ 8, 18, 28],
       [ 9, 19, 29]])

In [143]:
# a.flat returns a numpy.flatiter object , this is the only way to acquire a flatiter object.
# The flatiter enables us to loop through an array as if it is a flat array
for i in a.flat:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
